// Installing Ranger -> Archer kit

// Defines a work-around for a buggy implementation of opcode 122 (Create inventory item) in the Enhanced Editions
ACTION_IF (GAME_IS ~bgee iwdee~) BEGIN
  OUTER_TEXT_SPRINT spl_arrow "A7#ImprovedArcher/kit/ee/A7#IN04A.SPL"
  OUTER_TEXT_SPRINT spl_bolt  "A7#ImprovedArcher/kit/ee/A7#IN04B.SPL"
END ELSE BEGIN
  OUTER_TEXT_SPRINT spl_arrow "A7#ImprovedArcher/kit/A7#IN04A.SPL"
  OUTER_TEXT_SPRINT spl_bolt  "A7#ImprovedArcher/kit/A7#IN04B.SPL"
END
OUTER_SET help_strref = RESOLVE_STR_REF(@1100)    // Archer kit description

// Updating Archer description and ability table
COPY_EXISTING ~KITLIST.2DA~ ~override~
  COUNT_2DA_COLS numCols
  COUNT_2DA_ROWS numCols numRows
  SET found = 0
  FOR (row = 0; row < numRows && found < 1; row += 1) BEGIN
    READ_2DA_ENTRY row 1 numCols value
    PATCH_IF (~%value%~ STRING_EQUAL_CASE ~FERALAN~) BEGIN
      SET_2DA_ENTRY %row% 4 %numCols% ~%help_strref%~
      SET_2DA_ENTRY %row% 5 %numCols% ~CLABA7R1~
      found = 1
    END
  END

// Limiting weapon styles
COPY_EXISTING ~WEAPPROF.2DA~ ~override~
  COUNT_2DA_COLS numCols
  COUNT_2DA_ROWS numCols numRows
  SET found = 0
  FOR (row = 0; row < numRows && found < 4; row += 1) BEGIN
    READ_2DA_ENTRY row 0 numCols value
    PATCH_IF (~%value%~ STRING_EQUAL_CASE ~2HANDED~) BEGIN
      SET_2DA_ENTRY %row% 36 %numCols% ~1~
      found += 1
    END ELSE PATCH_IF (~%value%~ STRING_EQUAL_CASE ~SWORDANDSHIELD~) BEGIN
      SET_2DA_ENTRY %row% 36 %numCols% ~1~
      found += 1
    END ELSE PATCH_IF (~%value%~ STRING_EQUAL_CASE ~SINGLEWEAPON~) BEGIN
      SET_2DA_ENTRY %row% 36 %numCols% ~1~
      found += 1
    END ELSE PATCH_IF (~%value%~ STRING_EQUAL_CASE ~2WEAPON~) BEGIN
      SET_2DA_ENTRY %row% 36 %numCols% ~2~
      found += 1
    END
  END

// Modifying DEX and CON requirements
COPY_EXISTING ~ABCLASRQ.2DA~ ~override~
  COUNT_2DA_COLS numCols
  COUNT_2DA_ROWS numCols numRows
  SET found = 0
  FOR (row = 0; row < numRows && found < 1; row += 1) BEGIN
    READ_2DA_ENTRY row 0 numCols value
    PATCH_IF (~%value%~ STRING_EQUAL_CASE ~FERALAN~) BEGIN
      SET_2DA_ENTRY %row% 2 %numCols% ~14~
      SET_2DA_ENTRY %row% 3 %numCols% ~13~
      found = 1
    END
  END

// Setting CON penalty
COPY_EXISTING ~ABCLSMOD.2DA~ ~override~
  COUNT_2DA_COLS numCols
  COUNT_2DA_ROWS numCols numRows
  SET found = 0
  FOR (row = 0; row < numRows && found < 1; row += 1) BEGIN
    READ_2DA_ENTRY row 0 numCols value
    PATCH_IF (~%value%~ STRING_EQUAL_CASE ~FERALAN~) BEGIN
      SET_2DA_ENTRY %row% 3 %numCols% ~-1~
      found = 1
    END
  END

// Setting new HLA table
COPY_EXISTING ~LUABBR.2DA~ ~override~
  COUNT_2DA_COLS numCols
  COUNT_2DA_ROWS numCols numRows
  SET found = 0
  FOR (row = 0; row < numRows && found < 1; row += 1) BEGIN
    READ_2DA_ENTRY row 0 numCols value
    PATCH_IF (~%value%~ STRING_EQUAL_CASE ~FERALAN~) BEGIN
      SET_2DA_ENTRY %row% 1 %numCols% ~A7ra1~
      found = 1
    END
  END

ACTION_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
  // Updating Archer description
  COPY_EXISTING ~CLASTEXT.2DA~ ~override~
    COUNT_2DA_COLS numCols
    COUNT_2DA_ROWS numCols numRows
    SET found = 0
    FOR (row = 0; row < numRows && found < 2; row += 1) BEGIN
      READ_2DA_ENTRY row 0 numCols value
      PATCH_IF (~%value%~ STRING_EQUAL_CASE ~ARCHER~) BEGIN
        SET_2DA_ENTRY %row% 4 %numCols% ~%help_strref%~
        found += 1
      END ELSE PATCH_IF (~%value%~ STRING_EQUAL_CASE ~FALLEN_ARCHER~) BEGIN
        SET_2DA_ENTRY %row% 4 %numCols% ~%help_strref%~
        found += 1
      END
    END

  COPY ~A7#ImprovedArcher/kit/ee/A7#IARO1.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IBLT1.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN01B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN02B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN03B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN04B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN4AB.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN4BB.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN0AB.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN0BB.SPL~ ~override~
END ELSE BEGIN
  COPY ~A7#ImprovedArcher/kit/A7#IARO1.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IBLT1.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN01B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN02B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN03B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN04B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN4AB.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN4BB.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN0AB.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN0BB.SPL~ ~override~
END

ACTION_IF (GAME_IS ~iwdee~) BEGIN
  COPY ~A7#ImprovedArcher/kit/CLABA7R1_iwd.2DA~ ~override/CLABA7R1.2DA~
END ELSE BEGIN
  COPY ~A7#ImprovedArcher/kit/CLABA7R1_bg.2DA~ ~override/CLABA7R1.2DA~
END

COPY ~A7#ImprovedArcher/kit/A7#IN04.2DA~  ~override~
     ~A7#ImprovedArcher/kit/LUA7RA1.2DA~  ~override~
     ~A7#ImprovedArcher/kit/A7#IN11A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN11B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN11C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN12A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN12B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN12C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN13A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN13B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN13C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN14A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN14B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN14C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN21A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN21B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN21C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN21D.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN21E.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN21F.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN22A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN22B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN22C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN22D.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN22E.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN22F.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN23A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN23B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN23C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN23D.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN23E.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN23F.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN24A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN24B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN24C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN24D.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN24E.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN24F.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN25A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN25B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN25C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN25D.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN25E.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN25F.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN31A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN32A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN33A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN34A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN41A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN41B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN42A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN42B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN43A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN43B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN44A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN44B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN45A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN45B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN03.PRO~  ~override~
     ~A7#ImprovedArcher/kit/A7#IN05.SPL~  ~override~
     ~A7#ImprovedArcher/kit/A7#ENTG.BAM~  ~override~
     ~A7#ImprovedArcher/kit/A7#ENTG1.VVC~ ~override~


// Ability: Power Shot
COPY ~A7#ImprovedArcher/kit/A7#IN01.SPL~ ~override~
  SAY NAME1 @1000   // Power Shot
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    SAY UNIDENTIFIED_DESC @2001   // Power Shot...
  END


// Ability: Rooted Shot
COPY ~A7#ImprovedArcher/kit/A7#IN02.SPL~ ~override~
  SAY NAME1 @1001   // Rooted Shot
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    SAY UNIDENTIFIED_DESC @2002   // Rooted Shot...
  END


// Ability: Explosive Shot
ADD_PROJECTILE ~A7#ImprovedArcher/kit/A7#IN03.PRO~
COPY ~A7#ImprovedArcher/kit/A7#IN03.SPL~ ~override~
  SAY NAME1 @1002   // Explosive Shot
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    SAY UNIDENTIFIED_DESC @2003   // Explosive Shot...
  END
COPY ~A7#ImprovedArcher/kit/A7#IN31A.SPL~  ~override~
     ~A7#ImprovedArcher/kit/A7#IN32A.SPL~  ~override~
     ~A7#ImprovedArcher/kit/A7#IN33A.SPL~  ~override~
     ~A7#ImprovedArcher/kit/A7#IN34A.SPL~  ~override~
  SAY NAME1 @1002   // Explosive Shot
  READ_LONG 0x64 "ability_ofs"
  READ_SHORT 0x68 "ability_num"
  FOR (ability = 0; ability < ability_num; ability += 1) BEGIN
    WRITE_SHORT (ability_ofs + ability*0x28 + 0x26) %A7#IN03%
  END


// Setting common shot ability properties
COPY_EXISTING ~A7#IN01.SPL~ ~override~
              ~A7#IN02.SPL~ ~override~
              ~A7#IN03.SPL~ ~override~
  READ_LONG 0x6a "effects_ofs"
  WHILE (effects_ofs < SOURCE_SIZE) BEGIN
    READ_SHORT effects_ofs "fx_type"
    PATCH_IF (fx_type == 206) BEGIN   // Protection from spell (206)
      SAY (effects_ofs + 4) @1016   // You can't use another shot ability while the current effect is active.
    END
    effects_ofs += 0x30
  END

// Ability: Create Blessed Ammunition
COPY ~A7#ImprovedArcher/kit/A7#IN04.SPL~ ~override~
  SAY NAME1 @1003   // Create Blessed Ammunition
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    SAY UNIDENTIFIED_DESC @2004   // Create Spiritual Ammunition...
  END

COPY ~%spl_arrow%~ ~override~
  SAY NAME1 @1004   // Create Blessed Arrows
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    SAY UNIDENTIFIED_DESC @2005   // Create Spiritual Arrows...
  END
  READ_LONG 0x6a "effects_ofs"
  WHILE (effects_ofs < SOURCE_SIZE) BEGIN
    READ_SHORT effects_ofs "fx_type"
    PATCH_IF (fx_type == 139) BEGIN   // Display string (139)
      SAY (effects_ofs + 4) @1014   // Blessed Arrows created
    END
    effects_ofs += 0x30
  END

COPY ~%spl_bolt%~ ~override~
  SAY NAME1 @1005   // Create Blessed Bolts
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    SAY UNIDENTIFIED_DESC @2006   // Create Spiritual Bolts...
  END
  READ_LONG 0x6a "effects_ofs"
  WHILE (effects_ofs < SOURCE_SIZE) BEGIN
    READ_SHORT effects_ofs "fx_type"
    PATCH_IF (fx_type == 139) BEGIN   // Display string (139)
      SAY (effects_ofs + 4) @1015   // Blessed Bolts created
    END
    effects_ofs += 0x30
  END

// Blessed Arrows and Bolts
COPY ~A7#ImprovedArcher/kit/A7#INARA.ITM~ ~override~
  SAY NAME2 @1006   // Blessed Arrow +1
  SAY IDENTIFIED_DESC @1101   // This is an arrow that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END

COPY ~A7#ImprovedArcher/kit/A7#INARB.ITM~ ~override~
  SAY NAME2 @1006   // Blessed Arrow +1
  SAY IDENTIFIED_DESC @1102   // This is an arrow that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END

COPY ~A7#ImprovedArcher/kit/A7#INARC.ITM~ ~override~
  SAY NAME2 @1007   // Blessed Arrow +2
  SAY IDENTIFIED_DESC @1103   // This is an arrow that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END

COPY ~A7#ImprovedArcher/kit/A7#INARD.ITM~ ~override~
  SAY NAME2 @1008   // Blessed Arrow +3
  SAY IDENTIFIED_DESC @1104   // This is an arrow that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END

COPY ~A7#ImprovedArcher/kit/A7#INARE.ITM~ ~override~
  SAY NAME2 @1009   // Blessed Arrow +4
  SAY IDENTIFIED_DESC @1105   // This is an arrow that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END

COPY ~A7#ImprovedArcher/kit/A7#INBTA.ITM~ ~override~
  SAY NAME2 @1010   // Blessed Bolt +1
  SAY IDENTIFIED_DESC @1106   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END

COPY ~A7#ImprovedArcher/kit/A7#INBTB.ITM~ ~override~
  SAY NAME2 @1010   // Blessed Bolt +1
  SAY IDENTIFIED_DESC @1107   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END

COPY ~A7#ImprovedArcher/kit/A7#INBTC.ITM~ ~override~
  SAY NAME2 @1011   // Blessed Bolt +2
  SAY IDENTIFIED_DESC @1108   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END

COPY ~A7#ImprovedArcher/kit/A7#INBTD.ITM~ ~override~
  SAY NAME2 @1012   // Blessed Bolt +3
  SAY IDENTIFIED_DESC @1109   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END

COPY ~A7#ImprovedArcher/kit/A7#INBTE.ITM~ ~override~
  SAY NAME2 @1013   // Blessed Bolt +4
  SAY IDENTIFIED_DESC @1110   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END


// Ability: Sure Shot
COPY ~A7#ImprovedArcher/kit/A7#IN0A.SPL~ ~override~
  SAY NAME1 @1017   // Sure Shot
  SAY UNIDENTIFIED_DESC @1111   // Sure Shot...


// Ability: Missile Trap
COPY ~A7#ImprovedArcher/kit/A7#IN0B.SPL~ ~override~
  SAY NAME1 @1018   // Missile Trap
  SAY UNIDENTIFIED_DESC @1112   // Set Missile Trap...

