// Common base for all installed kits

// Work-around for a buggy implementation of opcode 122 (Create inventory item) in the Enhanced Editions patch 1.x
ACTION_IF (GAME_IS ~iwdee~ && NOT FILE_EXISTS_IN_GAME ~achievem.2da~) BEGIN
  OUTER_TEXT_SPRINT spl_arrow "A7#ImprovedArcher/kit/ee/A7#IN04A.SPL"
  OUTER_TEXT_SPRINT spl_bolt  "A7#ImprovedArcher/kit/ee/A7#IN04B.SPL"
  OUTER_TEXT_SPRINT spl_bullet  "A7#ImprovedArcher/kit/ee/A7#IN04C.SPL"
END ELSE BEGIN
  OUTER_TEXT_SPRINT spl_arrow "A7#ImprovedArcher/kit/A7#IN04A.SPL"
  OUTER_TEXT_SPRINT spl_bolt  "A7#ImprovedArcher/kit/A7#IN04B.SPL"
  OUTER_TEXT_SPRINT spl_bullet  "A7#ImprovedArcher/kit/A7#IN04C.SPL"
END

ACTION_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
  COPY ~A7#ImprovedArcher/kit/ee/A7#IARO1.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IBLT1.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IBUL1.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN01B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN02B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN03B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN04B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN4AB.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN4BB.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN4CB.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN0AB.BAM~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN0BB.SPL~ ~override~
       ~A7#ImprovedArcher/kit/ee/A7#IN06.SPL~  ~override~
END ELSE BEGIN
  COPY ~A7#ImprovedArcher/kit/A7#IARO1.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IBLT1.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IBUL1.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN01B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN02B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN03B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN04B.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN4AB.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN4BB.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN4CB.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN0AB.BAM~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN0BB.SPL~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN06.SPL~  ~override~
       ~A7#ImprovedArcher/kit/A7#IN06A.EFF~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN06B.EFF~ ~override~
       ~A7#ImprovedArcher/kit/A7#IN06C.EFF~ ~override~
END

COPY ~A7#ImprovedArcher/kit/A7#IN04.2DA~  ~override~
     ~A7#ImprovedArcher/kit/A7#IN07.2DA~  ~override~
     ~A7#ImprovedArcher/kit/LUA7RA1.2DA~  ~override~
     ~A7#ImprovedArcher/kit/A7#IN11A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN11B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN11C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN12A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN12B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN12C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN13A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN13B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN13C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN14A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN14B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN14C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN21A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN21B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN21C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN21D.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN21E.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN21F.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN22A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN22B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN22C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN22D.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN22E.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN22F.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN23A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN23B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN23C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN23D.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN23E.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN23F.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN24A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN24B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN24C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN24D.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN24E.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN24F.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN25A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN25B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN25C.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN25D.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN25E.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN25F.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN31A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN32A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN33A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN34A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN41A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN41B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN42A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN42B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN43A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN43B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN44A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN44B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN45A.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN45B.EFF~ ~override~
     ~A7#ImprovedArcher/kit/A7#IN03.PRO~  ~override~
     ~A7#ImprovedArcher/kit/A7#IN05.SPL~  ~override~
     ~A7#ImprovedArcher/kit/A7#ENTG.BAM~  ~override~
     ~A7#ImprovedArcher/kit/A7#ENTG1.VVC~ ~override~

// Initializing user-defined status icons for shot abilities (EE-only)
ACTION_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
  COPY_EXISTING ~STATDESC.2DA~ ~override~
    SET icon_index = 82
    SET icon_indices = 0
    COUNT_2DA_COLS numCols
    PATCH_IF (numCols > 2) BEGIN
      DEFINE_ASSOCIATIVE_ARRAY icon_defs BEGIN 
        1000 => ~A7#IN01D~
        1001 => ~A7#IN02D~
        1002 => ~A7#IN03D~
        1017 => ~A7#IN0AD~
      END
      READ_2DA_ENTRIES_NOW ~tbl_items~ numCols
      FOR (row = 0; row < tbl_items; ++row) BEGIN
        READ_2DA_ENTRY_FORMER ~tbl_items~ row 0 cur_idx
        PATCH_IF (IS_AN_INT ~cur_idx~) BEGIN
          READ_2DA_ENTRY_FORMER ~tbl_items~ row 2 cur_resref
          SET match = 0
          PHP_EACH icon_defs AS ref => icn_name BEGIN
            PATCH_IF (NOT match && ~%cur_resref%~ STR_EQ ~%icn_name%~) BEGIN
              SET $icon_indices(~%icn_name%~) = cur_idx
              SET icon_indices += 1
              SET match = 1
            END
          END
          PATCH_IF (cur_idx > icon_index) BEGIN
            SET icon_index = cur_idx
          END
        END
      END
    END

  ACTION_IF (icon_index > 82 && icon_indices < 4) BEGIN
    ACTION_PHP_EACH icon_defs AS ref => icn_name BEGIN
      ACTION_IF (NOT VARIABLE_IS_SET $icon_indices(~%icn_name%~)) BEGIN
        OUTER_SET icon_index += 1
        OUTER_SET cur_strref = RESOLVE_STR_REF((AT ref))
        OUTER_TEXT_SPRINT icon_row ~%icon_index% %cur_strref% %icn_name%~
        APPEND ~STATDESC.2DA~ ~%icon_row%~
        OUTER_SET $icon_indices(~%icn_name%~) = icon_index
        OUTER_SET icon_indices += 1
      END
    END
    COPY_EXISTING ~STATDESC.2DA~ ~override~
      PRETTY_PRINT_2DA
    BUT_ONLY
  END

  COPY ~A7#ImprovedArcher/kit/ee/A7#IN01D.BAM~ ~override~
  COPY ~A7#ImprovedArcher/kit/ee/A7#IN02D.BAM~ ~override~
  COPY ~A7#ImprovedArcher/kit/ee/A7#IN03D.BAM~ ~override~
  COPY ~A7#ImprovedArcher/kit/ee/A7#IN0AD.BAM~ ~override~
END ELSE BEGIN
  OUTER_SET icon_index = 82
END


// Ability: Power Shot
COPY ~A7#ImprovedArcher/kit/A7#IN01.SPL~ ~override~
  SAY NAME1 @1000   // Power Shot
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    SAY UNIDENTIFIED_DESC @2001   // Power Shot...
    PATCH_IF (VARIABLE_IS_SET $icon_indices(~A7#IN01D~)) BEGIN
      SET idx = $icon_indices(~A7#IN01D~)
      LPF ALTER_EFFECT
      INT_VAR
        check_globals     = 0
        check_headers     = 1
        match_opcode      = 142   // Display portrait icon
        match_parameter2  = 82    // Called Shot icon
        parameter2        = idx
      END
    END
  END


// Ability: Rooting Shot
COPY ~A7#ImprovedArcher/kit/A7#IN02.SPL~ ~override~
  SAY NAME1 @1001   // Rooting Shot
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    SAY UNIDENTIFIED_DESC @2002   // Rooting Shot...
    PATCH_IF (VARIABLE_IS_SET $icon_indices(~A7#IN02D~)) BEGIN
      SET idx = $icon_indices(~A7#IN02D~)
      LPF ALTER_EFFECT
      INT_VAR
        check_globals     = 0
        check_headers     = 1
        match_opcode      = 142   // Display portrait icon
        match_parameter2  = 82    // Called Shot icon
        parameter2        = idx
      END
    END
  END


// Ability: Explosive Shot
OUTER_SET ~A7#IN03~ = IDS_OF_SYMBOL(~projectl~ ~A7#IN03~) + 1
ACTION_IF (~A7#IN03~ = 0) BEGIN
  ADD_PROJECTILE ~A7#ImprovedArcher/kit/A7#IN03.PRO~
END
COPY ~A7#ImprovedArcher/kit/A7#IN03.SPL~ ~override~
  SAY NAME1 @1002   // Explosive Shot
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    SAY UNIDENTIFIED_DESC @2003   // Explosive Shot...
    PATCH_IF (VARIABLE_IS_SET $icon_indices(~A7#IN03D~)) BEGIN
      SET idx = $icon_indices(~A7#IN03D~)
      LPF ALTER_EFFECT
      INT_VAR
        check_globals     = 0
        check_headers     = 1
        match_opcode      = 142   // Display portrait icon
        match_parameter2  = 82    // Called Shot icon
        parameter2        = idx
      END
    END
  END
COPY ~A7#ImprovedArcher/kit/A7#IN31A.SPL~  ~override~
     ~A7#ImprovedArcher/kit/A7#IN32A.SPL~  ~override~
     ~A7#ImprovedArcher/kit/A7#IN33A.SPL~  ~override~
     ~A7#ImprovedArcher/kit/A7#IN34A.SPL~  ~override~
  SAY NAME1 @1002   // Explosive Shot
  READ_LONG 0x64 "ability_ofs"
  READ_SHORT 0x68 "ability_num"
  FOR (ability = 0; ability < ability_num; ability += 1) BEGIN
    WRITE_SHORT (ability_ofs + ability*0x28 + 0x26) %A7#IN03%
  END


// Setting common shot ability properties
COPY_EXISTING ~A7#IN01.SPL~ ~override~
              ~A7#IN02.SPL~ ~override~
              ~A7#IN03.SPL~ ~override~
  READ_LONG 0x6a "effects_ofs"
  WHILE (effects_ofs < SOURCE_SIZE) BEGIN
    READ_SHORT effects_ofs "fx_type"
    PATCH_IF (fx_type == 206) BEGIN   // Protection from spell (206)
      SAY (effects_ofs + 4) @1016   // You can't use another shot ability while the current effect is active.
    END
    effects_ofs += 0x30
  END
  BUT_ONLY

// Ability: Create Blessed Ammunition
COPY ~A7#ImprovedArcher/kit/A7#IN04.SPL~ ~override~
  SAY NAME1 @1003   // Create Blessed Ammunition
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    SAY UNIDENTIFIED_DESC @2004   // Create Spiritual Ammunition...
  END

COPY ~A7#ImprovedArcher/kit/A7#IN07.SPL~ ~override~
  SAY NAME1 @1003   // Create Blessed Ammunition
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    SAY UNIDENTIFIED_DESC @2008   // Create Spiritual Ammunition...
  END

COPY ~%spl_arrow%~ ~override~
  SAY NAME1 @1004   // Create Blessed Arrows
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    SAY UNIDENTIFIED_DESC @2005   // Create Spiritual Arrows...
  END
  READ_LONG 0x6a "effects_ofs"
  WHILE (effects_ofs < SOURCE_SIZE) BEGIN
    READ_SHORT effects_ofs "fx_type"
    PATCH_IF (fx_type == 139) BEGIN   // Display string (139)
      SAY (effects_ofs + 4) @1014   // Blessed Arrows created
    END
    effects_ofs += 0x30
  END

COPY ~%spl_bolt%~ ~override~
  SAY NAME1 @1005   // Create Blessed Bolts
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    SAY UNIDENTIFIED_DESC @2006   // Create Spiritual Bolts...
  END
  READ_LONG 0x6a "effects_ofs"
  WHILE (effects_ofs < SOURCE_SIZE) BEGIN
    READ_SHORT effects_ofs "fx_type"
    PATCH_IF (fx_type == 139) BEGIN   // Display string (139)
      SAY (effects_ofs + 4) @1015   // Blessed Bolts created
    END
    effects_ofs += 0x30
  END

COPY ~%spl_bullet%~ ~override~
  SAY NAME1 @1023   // Create Blessed Bullets
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    SAY UNIDENTIFIED_DESC @2007   // Create Spiritual Bullets...
  END
  READ_LONG 0x6a "effects_ofs"
  WHILE (effects_ofs < SOURCE_SIZE) BEGIN
    READ_SHORT effects_ofs "fx_type"
    PATCH_IF (fx_type == 139) BEGIN   // Display string (139)
      SAY (effects_ofs + 4) @1028   // Blessed Bullets created
    END
    effects_ofs += 0x30
  END

// Blessed Arrows, Bolts and Bullets
COPY ~A7#ImprovedArcher/kit/A7#INARA.ITM~ ~override~
  SAY NAME2 @1006   // Blessed Arrow +1
  SAY IDENTIFIED_DESC @1101   // This is an arrow that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible arrow projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 2 END
  END

COPY ~A7#ImprovedArcher/kit/A7#INARB.ITM~ ~override~
  SAY NAME2 @1006   // Blessed Arrow +1
  SAY IDENTIFIED_DESC @1102   // This is an arrow that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible arrow projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 2 END
  END

COPY ~A7#ImprovedArcher/kit/A7#INARC.ITM~ ~override~
  SAY NAME2 @1007   // Blessed Arrow +2
  SAY IDENTIFIED_DESC @1103   // This is an arrow that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible arrow projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 2 END
  END

COPY ~A7#ImprovedArcher/kit/A7#INARD.ITM~ ~override~
  SAY NAME2 @1008   // Blessed Arrow +3
  SAY IDENTIFIED_DESC @1104   // This is an arrow that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible arrow projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 2 END
  END

COPY ~A7#ImprovedArcher/kit/A7#INARE.ITM~ ~override~
  SAY NAME2 @1009   // Blessed Arrow +4
  SAY IDENTIFIED_DESC @1105   // This is an arrow that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible arrow projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 2 END
  END

COPY ~A7#ImprovedArcher/kit/A7#INBTA.ITM~ ~override~
  SAY NAME2 @1010   // Blessed Bolt +1
  SAY IDENTIFIED_DESC @1106   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible bolt projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 12 END
  END

COPY ~A7#ImprovedArcher/kit/A7#INBTB.ITM~ ~override~
  SAY NAME2 @1010   // Blessed Bolt +1
  SAY IDENTIFIED_DESC @1107   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible bolt projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 12 END
  END

COPY ~A7#ImprovedArcher/kit/A7#INBTC.ITM~ ~override~
  SAY NAME2 @1011   // Blessed Bolt +2
  SAY IDENTIFIED_DESC @1108   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible bolt projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 12 END
  END

COPY ~A7#ImprovedArcher/kit/A7#INBTD.ITM~ ~override~
  SAY NAME2 @1012   // Blessed Bolt +3
  SAY IDENTIFIED_DESC @1109   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible bolt projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 12 END
  END

COPY ~A7#ImprovedArcher/kit/A7#INBTE.ITM~ ~override~
  SAY NAME2 @1013   // Blessed Bolt +4
  SAY IDENTIFIED_DESC @1110   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible bolt projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 12 END
  END

COPY ~A7#ImprovedArcher/kit/A7#INBUA.ITM~ ~override~
  SAY NAME2 @1024   // Blessed Bullet +1
  SAY IDENTIFIED_DESC @1120   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible bolt projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 17 END
  END

COPY ~A7#ImprovedArcher/kit/A7#INBUB.ITM~ ~override~
  SAY NAME2 @1024   // Blessed Bullet +1
  SAY IDENTIFIED_DESC @1121   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible bolt projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 17 END
  END

COPY ~A7#ImprovedArcher/kit/A7#INBUC.ITM~ ~override~
  SAY NAME2 @1025   // Blessed Bullet +2
  SAY IDENTIFIED_DESC @1122   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible bolt projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 17 END
  END

COPY ~A7#ImprovedArcher/kit/A7#INBUD.ITM~ ~override~
  SAY NAME2 @1026   // Blessed Bullet +3
  SAY IDENTIFIED_DESC @1123   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible bolt projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 17 END
  END

COPY ~A7#ImprovedArcher/kit/A7#INBUE.ITM~ ~override~
  SAY NAME2 @1027   // Blessed Bullet +4
  SAY IDENTIFIED_DESC @1124   // This is an bolt that has been blessed by the Archer's worshipped god or goddess...
  PATCH_IF (GAME_IS ~iwdee~) BEGIN
    WRITE_ASCII 0x58 ~~ #8    // Description image
  END
  PATCH_IF (GAME_IS ~tob bgt~) BEGIN // apply compatible bolt projectile
    LPF ALTER_ITEM_HEADER INT_VAR projectile = 17 END
  END


// Ability: Sure Shot
COPY ~A7#ImprovedArcher/kit/A7#IN0A.SPL~ ~override~
  SAY NAME1 @1017   // Sure Shot
  SAY UNIDENTIFIED_DESC @1111   // Sure Shot...
  PATCH_IF (GAME_IS ~bgee bg2ee eet iwdee~ && VARIABLE_IS_SET $icon_indices(~A7#IN0AD~)) BEGIN
    SET idx = $icon_indices(~A7#IN0AD~)
    LPF ALTER_EFFECT
    INT_VAR
      check_globals     = 0
      check_headers     = 1
      match_opcode      = 142   // Display portrait icon
      match_parameter2  = 82    // Called Shot icon
      parameter2        = idx
    END
  END


// Ability: Missile Trap
COPY ~A7#ImprovedArcher/kit/A7#IN0B.SPL~ ~override~
  SAY NAME1 @1018   // Missile Trap
  SAY UNIDENTIFIED_DESC @1112   // Set Missile Trap...
